/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_transwarp_stellardb_booster_BoosterNative */

#ifndef _Included_io_transwarp_stellardb_booster_BoosterNative
#define _Included_io_transwarp_stellardb_booster_BoosterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    native_reload_library
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_native_1reload_1library
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    database_init
 * Signature: (Ljava/lang/String;JZZJ)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_database_1init
  (JNIEnv *, jclass, jstring, jlong, jboolean, jboolean, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    database_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDatabase;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_database_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    database_set_logging_level
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_database_1set_1logging_1level
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_init
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDatabase;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_set_max_num_thread_for_exec
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;J)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1set_1max_1num_1thread_1for_1exec
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_get_max_num_thread_for_exec
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1get_1max_1num_1thread_1for_1exec
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_query
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;Ljava/lang/String;)Lio/transwarp/stellardb_booster/BoosterQueryResult;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1query
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_prepare
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;Ljava/lang/String;)Lio/transwarp/stellardb_booster/BoosterPreparedStatement;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1prepare
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_execute
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;Lio/transwarp/stellardb_booster/BoosterPreparedStatement;Ljava/util/Map;)Lio/transwarp/stellardb_booster/BoosterQueryResult;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1execute
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_interrupt
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1interrupt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    connection_set_query_timeout
 * Signature: (Lio/transwarp/stellardb_booster/BoosterConnection;J)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_connection_1set_1query_1timeout
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    prepared_statement_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterPreparedStatement;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_prepared_1statement_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    prepared_statement_allow_active_transaction
 * Signature: (Lio/transwarp/stellardb_booster/BoosterPreparedStatement;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_prepared_1statement_1allow_1active_1transaction
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    prepared_statement_is_success
 * Signature: (Lio/transwarp/stellardb_booster/BoosterPreparedStatement;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_prepared_1statement_1is_1success
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    prepared_statement_get_error_message
 * Signature: (Lio/transwarp/stellardb_booster/BoosterPreparedStatement;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_prepared_1statement_1get_1error_1message
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_is_success
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1is_1success
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_error_message
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1error_1message
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_num_columns
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1num_1columns
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_column_name
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1column_1name
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_column_data_type
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;J)Lio/transwarp/stellardb_booster/BoosterDataType;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1column_1data_1type
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_num_tuples
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1num_1tuples
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_query_summary
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Lio/transwarp/stellardb_booster/BoosterQuerySummary;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1query_1summary
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_has_next
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1has_1next
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_get_next
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Lio/transwarp/stellardb_booster/BoosterFlatTuple;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1get_1next
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_to_string
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1to_1string
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    query_result_reset_iterator
 * Signature: (Lio/transwarp/stellardb_booster/BoosterQueryResult;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_query_1result_1reset_1iterator
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    flat_tuple_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterFlatTuple;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_flat_1tuple_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    flat_tuple_get_value
 * Signature: (Lio/transwarp/stellardb_booster/BoosterFlatTuple;J)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_flat_1tuple_1get_1value
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    flat_tuple_to_string
 * Signature: (Lio/transwarp/stellardb_booster/BoosterFlatTuple;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_flat_1tuple_1to_1string
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_create
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataTypeID;Lio/transwarp/stellardb_booster/BoosterDataType;J)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1create
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_clone
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)Lio/transwarp/stellardb_booster/BoosterDataType;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1clone
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_equals
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;Lio/transwarp/stellardb_booster/BoosterDataType;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1equals
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_get_id
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)Lio/transwarp/stellardb_booster/BoosterDataTypeID;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1get_1id
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_get_child_type
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)Lio/transwarp/stellardb_booster/BoosterDataType;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1get_1child_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    data_type_get_fixed_num_elements_in_list
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_data_1type_1get_1fixed_1num_1elements_1in_1list
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_create_null
 * Signature: ()Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1create_1null
  (JNIEnv *, jclass);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_create_null_with_data_type
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1create_1null_1with_1data_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_is_null
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1is_1null
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_set_null
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;Z)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1set_1null
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_create_default
 * Signature: (Lio/transwarp/stellardb_booster/BoosterDataType;)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1create_1default
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_create_value
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1create_1value
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_clone
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1clone
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_copy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;Lio/transwarp/stellardb_booster/BoosterValue;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1copy
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_destroy
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)V
 */
JNIEXPORT void JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_list_size
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1list_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_list_element
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1list_1element
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_data_type
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterDataType;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1data_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_value
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1value
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_to_string
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1to_1string
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_get_id
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterInternalID;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1get_1id
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_id
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterInternalID;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1id
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_get_label_name
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1get_1label_1name
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_get_property_size
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1get_1property_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_get_property_name_at
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1get_1property_1name_1at
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_get_property_value_at
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1get_1property_1value_1at
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    node_val_to_string
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_node_1val_1to_1string
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_src_id
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterInternalID;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1src_1id
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_dst_id
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterInternalID;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1dst_1id
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_label_name
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1label_1name
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_property_size
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1property_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_property_name_at
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1property_1name_1at
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_get_property_value_at
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Lio/transwarp/stellardb_booster/BoosterValue;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1get_1property_1value_1at
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rel_val_to_string
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rel_1val_1to_1string
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_struct_field_name
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1struct_1field_1name
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    value_get_struct_index
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_value_1get_1struct_1index
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rdf_variant_get_data_type
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Lio/transwarp/stellardb_booster/BoosterDataType;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rdf_1variant_1get_1data_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    rdf_variant_get_value
 * Signature: (Lio/transwarp/stellardb_booster/BoosterValue;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_rdf_1variant_1get_1value
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_get_1version
  (JNIEnv *, jclass);

/*
 * Class:     io_transwarp_stellardb_booster_BoosterNative
 * Method:    get_storage_version
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_transwarp_stellardb_1booster_BoosterNative_get_1storage_1version
  (JNIEnv *, jclass);


JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved);

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *reserved);

#ifdef __cplusplus
}
#endif
#endif
